### ISSUE TITLE
Have U-Boot or EPCS load the bitfile on boot

### ISSUE THREAD

**Issue by bradgrantham** [lkesteloot/alice#19]
Need to recompile uboot so that fpga2sdram_handoff=0x00000333 or put that by hand in the bootcmd variable

**Comment by lkesteloot** [comment]
To do:

- [x] Change bridge to 0xFFF.
- [x] Convert bitfile to correct format.
- [x] Put bitfile in file system.
- [x] Load bitfile in U-Boot.
- [x] Fix dip switches on board.
- [x] Load bitfile into FPGA.

**Comment by lkesteloot** [comment]
According to [this page](https://rocketboards.org/foswiki/Documentation/LoadingFPGAFromUBoot), we want an RBF file:

    quartus_cpf -c <input file>.sof <output file>.rbf

Switches:

    up-up-down-up-up-up = uncompressed rbf

**Comment by lkesteloot** [comment]
Also: [Programming FPGA from HPS](https://rocketboards.org/foswiki/view/Documentation/GSRD131ProgrammingFPGA).

**Comment by lkesteloot** [comment]
Change 296bfd27 adds the boot script. The Google doc has the rest of the info.
