### ISSUE TITLE
Split out GPU functions into a separate library

### ISSUE THREAD

**Issue by bradgrantham** [lkesteloot/alice#33]
Right now there's the potential for drift between the gpu code in hardware_rasterizer.c and the other files.

All code interacting with the GPU should probably be in one C file.

**Comment by lkesteloot** [comment]
You mean the `cmd_draw()` functions, etc? I can take this one.

**Comment by bradgrantham** [comment]
Yeah and some sloppy gpu_ functions I wrote to do think like start the gpu,
wait on F2H_BUSY, etc.  And it would be nice to wrap access to gpo and gpi
to keep track of the previous brightness, etc.  Thank you!

**Comment by bradgrantham** [comment]
Mind if I do this over the weekend while you're gone?

**Comment by lkesteloot** [comment]
Fine by me.
