### ISSUE TITLE
Arena no longer compiles

### ISSUE THREAD

**Issue by lkesteloot** [lkesteloot/alice#45]
`M_PI` seems to be defined in `math.h`, which is included by `hardware_events.c`, but it still gives this error:

    ../libgl/hardware_events.c:108:38: error: ‘M_PI’ undeclared (first use in this function)
          value = theta_x_smoothed / (2 * M_PI) * 3600;

Note that `hardware_events.c` is included in logo and compiles fine there. Removing the flag `-std=c99` from the Arena Makefile results in successful compilation. I didn't check that change in because I didn't know why it was there.

**Comment by bradgrantham** [comment]
Compiles.
